### ISSUE TITLE
Dependencies uploaded!

### ISSUE THREAD

**Issue by LuisTJap** [dehrax/wochat#2]
Hi!
Thank you for your work but you should not upload your component dependencies directly, instead you should put all of them inside your bower.json

Best regards

**Comment by tskarhed** [comment]
Hi!
I have removed the `bower_components`folder in my latest commit.

For the sake of argument:
There are certain cases where one should add dependencies directly in the repository. See:
http://stackoverflow.com/questions/18128863/should-node-modules-folder-be-included-in-the-git-repository
